### PR TITLE
Update paths and file name according to documentation

### PR DESCRIPTION
**Pull request by stefanerwinmayer**
https://docs.sonarqube.org/latest/analysis/coverage/
https://docs.sonarqube.org/latest/analysis/external-issues/

### CODE REVIEW

**Comment by mwz** [comment]
Thanks for your PR @stefanerwinmayer.
This change would improve the integration with SonarScala, but it would break it for [sonar-scala](https://github.com/mwz/sonar-scala), which uses a different set of properties for scoverage and scapegoat. To make this work for both Scala plugins, we could use both sets of properties and automatically set them all (so in addition to the new properties that you added I'd also keep the old ones). This might result in sbt-sonar showing warnings about setting unused properties when running analysis using both SonarScala and sonar-scala (we'd need to check that it's not an error), but at least it's a quick way to make this work for both plugins. @BalmungSan does that sound ok to you?

**Comment by BalmungSan** [comment]
I think we either should change **sonar-scala** to have the same flags. Or to add a flag / setting to this plugin to indicate which sonar plugin one is using.

I prefer the last.

**Comment by mwz** [comment]
> add a flag / setting to this plugin to indicate which sonar plugin one is using

Yes, that would also be my preferred option 👍 I'd like to keep sonar-scala as the default option for compatibility reasons, but you could toggle a flag to switch over to SonarScala compatible properties. I'm trying to come up with any good names, but the best I've got so far is `sonarUseCommunityPlugin` which defaults to true and setting it to false toggles SonarScala compatibility. Can you think of any better alternatives?

**Comment by BalmungSan** [comment]
I am really bad a naming things, and I liked yours. Thus, no alternatives from my side.

**Comment by mwz** [comment]
Hi @stefanerwinmayer, does the solution I proposed above make sense to you? Is that something you would be able to contribute as a part of this PR?

**Comment by stefanerwinmayer** [comment]
> Hi @stefanerwinmayer, does the solution I proposed above make sense to you? Is that something you would be able to contribute as a part of this PR?

Yes I will do that.

**Comment by mwz** [comment]
Superseded by #117.

**Pull request closed without merging**
